### ISSUE TITLE
feature request : gravatar priority

### ISSUE THREAD

**Issue by icarteret** [tfrommen/adorable-avatars#1]
Hello,
thanks for this plugin, i love those cute faces ! it's great !
But i have an issue ( or a feature request ?).
I would like that users who already have a Gravatar keep their gravatar. Currently the plugin overwrite the gravatar.
I hope to post in the right place ...

**Comment by tfrommen** [comment]
Fixed with b50f3f8ac06305b716e1dcd62ccb8ec3cb10dd3b.
