### ISSUE TITLE
Got Error While Deleting

### ISSUE THREAD

**Issue by NoahDragon** [tfrommen/adorable-avatars#4]
#### Version Information

* PHP: 7.0
* WordPress: 4.7 

#### Steps to Reproduce

1. Start Wordpress in Docker
2. Add the adorable avatars plugin 
3. Delete it 

#### What I Expected

Delete Successfully

#### What Happened Instead

![image](https://cloud.githubusercontent.com/assets/5704064/21487978/cbd72b22-cba6-11e6-860f-bd39db8faf70.png)

#### Solution

Manually delete, but it is good to remove via the pulgin manager.

**Comment by tfrommen** [comment]
Thanks!

I just fixed this.
The problem was that the file with the `Avatar` class was not included in the `uninstall.php` file. ;)
